name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate Node.js version for your app

    - name: Install dependencies
      run: |
        npm install

    - name: Build the application
      run: |
        npm run build  # Replace with your build script if different

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: /  # The location of your app (e.g., / for the root)
        output_location: build  # The build output directory
        app_build_command: 'npm run build'  # Make sure this matches your build command
